Repository Tugduoff/RType, pull requests merged in 2024-10, with the labels that each got.

#73 Make `SparseArray` store constructors
  src/ECS/component/ComponentManager.hpp
  src/ECS/utilities/SparseArray.hpp
  src/ECS/utilities/ValueIterator.hpp
  src/GameEngine/GameEngine.hpp
Labels: refactor

#44 Visible component
  plugins/components/visible/CMakeLists.txt
  plugins/components/visible/Visible.cpp
  plugins/components/visible/Visible.hpp
  plugins/components/visible/tests/Main.cpp
Labels: game-engine

#74 :sparkles: Controllable component
  Actions.cpp
  Actions.hpp
  Keys.cpp
  Keys.hpp
  config/config.cfg
  plugins/components/controllable/CMakeLists.txt
  plugins/components/controllable/Controllable.cpp
  plugins/components/controllable/Controllable.hpp
  src/server/CMakeLists.txt
  src/server/Main.cpp
Labels: server, game-engine

#45 Health component
  plugins/components/health/CMakeLists.txt
  plugins/components/health/Health.cpp
  plugins/components/health/Health.hpp
  plugins/components/health/tests/Main.cpp
Labels: game-engine

#70 :memo: Doxygen docs
  CONTRIBUTING.md
  doc/Doxyfile
  doc/doxygen_custom.css
  flake.nix
  plugins/components/AComponent.hpp
  plugins/components/IComponent.hpp
  plugins/components/controllable/Controllable.hpp
  plugins/components/position/Position.hpp
  plugins/components/velocity/Velocity.hpp
  plugins/components/visible/Visible.hpp
  plugins/systems/ASystem.hpp
  plugins/systems/ISystem.hpp
  plugins/systems/config/Config.hpp
  plugins/systems/move/Move.hpp
  src/DLLoader/DLLoader.hpp
  src/ECS/registry/Registry.hpp
  src/ECS/utilities/SparseArray.hpp
  src/GameEngine/GameEngine.hpp
Labels: documentation

#48 Collider component
  plugins/components/collider/CMakeLists.txt
  plugins/components/collider/Collider.cpp
  plugins/components/collider/Collider.hpp
Labels: game-engine

#75 :sparkles: Make Component plugins `any_cast`
  plugins/components/AComponent.hpp
  plugins/components/IComponent.hpp
  plugins/components/collider/Collider.hpp
  plugins/components/controllable/Controllable.cpp
  plugins/components/controllable/Controllable.hpp
  plugins/components/health/Health.hpp
  plugins/components/position/Position.hpp
  plugins/components/velocity/Velocity.hpp
  plugins/components/visible/Visible.hpp
  src/ECS/component/ComponentManager.hpp
  src/GameEngine/GameEngine.hpp
  src/server/Main.cpp
Labels: enhancement, game-engine

#77 :adhesive_bandage: Fix cmake debug build
  build_plugins.sh
  build_rtype.sh
  build_scripts/build_debian_binary.sh
  build_scripts/build_fedora_binary.sh
  plugins/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci/cd

#76 :recycle: Refactor entrypoint and create a new entrypoint with params
  plugins/components/collider/Collider.cpp
  plugins/components/controllable/Controllable.cpp
  plugins/components/health/Health.cpp
  plugins/components/position/Position.cpp
  plugins/components/velocity/Velocity.cpp
  plugins/components/velocity/Velocity.hpp
  plugins/components/visible/Visible.cpp
  plugins/components/visible/Visible.hpp
  plugins/systems/config/Config.cpp
  src/DLLoader/DLLoader.hpp
  src/GameEngine/GameEngine.hpp
Labels: server, game-engine

#78 :recycle: Check & Fix components
  config/config.cfg
  plugins/components/AComponent.hpp
  plugins/components/collider/Collider.cpp
  plugins/components/collider/Collider.hpp
  plugins/components/health/Health.hpp
  plugins/components/position/Position.hpp
  plugins/components/visible/Visible.cpp
  plugins/components/visible/Visible.hpp
  src/server/Main.cpp
Labels: documentation, enhancement, server, game-engine

#82 :sparkles: Input system & Acceleration component
  config/config.cfg
  plugins/bin/systems/configSystems.cfg
  plugins/components/acceleration/Acceleration.cpp
  plugins/components/acceleration/Acceleration.hpp
  plugins/components/acceleration/CMakeLists.txt
  plugins/components/velocity/Velocity.cpp
  plugins/components/velocity/Velocity.hpp
  plugins/systems/input/CMakeLists.txt
  plugins/systems/input/Input.cpp
  plugins/systems/input/Input.hpp
  plugins/systems/move/Move.cpp
  src/server/Main.cpp
Labels: enhancement, server, game-engine

#81 :sparkles: Add events callbacks to ECS
  src/ECS/component/ComponentManager.hpp
  src/ECS/registry/Registry.cpp
  src/ECS/registry/Registry.hpp
  src/ECS/utilities/SparseArray.hpp
Labels: enhancement, game-engine

#83 Gun component
  plugins/components/gun/CMakeLists.txt
  plugins/components/gun/Gun.cpp
  plugins/components/gun/Gun.hpp
Labels: game-engine

#84 :sparkles: Sfml system
  Chrono.hpp
  assets/enemy.png
  assets/player.png
  config/config.cfg
  plugins/bin/systems/configSystems.cfg
  plugins/components/controllable/Controllable.cpp
  plugins/components/controllable/Controllable.hpp
  plugins/components/spriteId/CMakeLists.txt
  plugins/components/spriteId/SpriteID.cpp
  plugins/components/spriteId/SpriteID.hpp
  plugins/systems/input/Input.cpp
  plugins/systems/sfml/CMakeLists.txt
  plugins/systems/sfml/Display.cpp
  plugins/systems/sfml/Display.hpp
  plugins/systems/sfml/Input.cpp
  plugins/systems/sfml/Input.hpp
  plugins/systems/sfml/Sfml.cpp
  plugins/systems/sfml/Sfml.hpp
  plugins/systems/sfml/SpriteComponent.hpp
  src/server/Main.cpp
Labels: enhancement, game-engine, graphic

#86 🌐 Simple udp server
  src/CMakeLists.txt
  src/GameEngine/GameEngine.hpp
  src/client/CMakeLists.txt
  src/client/Main.cpp
  src/network/RTypeClient.cpp
  src/network/RTypeClient.hpp
  src/network/UDPConnection.cpp
  src/network/UDPConnection.hpp
  src/network/UDPServer.cpp
  src/network/UDPServer.hpp
  src/server/CMakeLists.txt
  src/server/Main.cpp
Labels: network

#87 :sparkles: Config spawn entities
  ECS/config/ConfigStruct.hpp
  config/config.cfg
  plugins/components/velocity/Velocity.hpp
  plugins/systems/config/Config.cpp
  plugins/systems/config/Config.hpp
  plugins/systems/move/Move.cpp
  src/ECS/registry/Registry.cpp
  src/ECS/registry/Registry.hpp
Labels: enhancement, game-engine, graphic

#88 Shooting system with projectiles creation
  assets/shot1.png
  config/config.cfg
  plugins/components/damage/CMakeLists.txt
  plugins/components/damage/Damage.cpp
  plugins/components/damage/Damage.hpp
  plugins/components/gun/Gun.cpp
  plugins/components/gun/Gun.hpp
  plugins/systems/input/Input.cpp
  plugins/systems/input/Input.hpp
  plugins/systems/sfml/Display.cpp
  src/server/Main.cpp
Labels: game-engine

#89 :sparkles: Entities shot
  assets/shot2.png
  config/config.cfg
  plugins/components/scale/CMakeLists.txt
  plugins/components/scale/Scale.cpp
  plugins/components/scale/Scale.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/attack/Attack.hpp
  plugins/systems/attack/CMakeLists.txt
  plugins/systems/sfml/Display.cpp
  src/client/Main.cpp
  src/client/configClient.cfg
  src/server/Main.cpp
  src/server/configServer.cfg
Labels: enhancement, game-engine

#90 :wrench: Fix udp server async infinite loop
  src/network/UDPServer.cpp
  src/network/UDPServer.hpp
  src/server/Main.cpp
Labels: network

#91 Death range component
  config/config.cfg
  plugins/components/deathRange/CMakeLists.txt
  plugins/components/deathRange/DeathRange.cpp
  plugins/components/deathRange/DeathRange.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/attack/Attack.hpp
  plugins/systems/input/Input.cpp
  plugins/systems/input/Input.hpp
  plugins/systems/move/Move.cpp
  plugins/systems/sfml/Display.cpp
  plugins/systems/sfml/Input.cpp
  src/ECS/entity/EntityManager.hpp
  src/ECS/utilities/SparseArray.hpp
  src/ECS/utilities/ValueIterator.hpp
  src/server/Main.cpp
Labels: game-engine

#92 Setup server callbacks
  src/GameEngine/GameEngine.hpp
  src/network/RTypeClient.cpp
  src/network/UDPServer.cpp
  src/network/UDPServer.hpp
  src/server/Main.cpp
  src/server/configServer.cfg
Labels: server, network

#96 :construction_worker: Create static.yml workflow that deploys the dox…
  .github/workflows/static.yml
Labels: enhancement, ci/cd

#99 :sparkles: Create SparseArray zipper
  flake.nix
  src/ECS/utilities/TupleUtils.hpp
  src/ECS/utilities/Zipper/GenericZipper.hpp
  src/ECS/utilities/Zipper/IndexedZipper.hpp
  src/ECS/utilities/Zipper/IndexedZipperIterator.hpp
  src/ECS/utilities/Zipper/Zipper.hpp
  src/ECS/utilities/Zipper/ZipperIterator.hpp
  tests/.gitignore
  tests/CMakeLists.txt
  tests/Zipper
  tests/indexed_zipper_tests.cpp
  tests/zipper_tests.cpp
Labels: enhancement

#94 :memo: Basic dev documentation
  CONTRIBUTING.md
  DebianDockerfile
  FedoraDockerfile
  README.md
  doc/Doxyfile
  plugins/components/controllable/CMakeLists.txt
  plugins/components/controllable/Controllable.hpp
  plugins/components/deathRange/DeathRange.hpp
  plugins/components/gun/Gun.hpp
  plugins/systems/config/Config.hpp
  plugins/systems/input/CMakeLists.txt
  plugins/systems/input/Input.cpp
  plugins/systems/sfml/CMakeLists.txt
  plugins/systems/sfml/Input.hpp
  plugins/systems/sfml/Texture.hpp
  release_files/DebianExecuteBinaryDockerfile
  release_files/FedoraExecuteBinaryDockerfile
  release_files/WindowsDockerfile
  release_files/build_scripts/build_debian_binary.sh
  release_files/build_scripts/build_fedora_binary.sh
  release_files/build_scripts/build_windows_binary.bat
  release_files/build_scripts/r-type_client.sh
  release_files/build_scripts/r-type_server.sh
  src/server/CMakeLists.txt
  src/server/Main.cpp
  src/utils/Actions.cpp
  src/utils/Actions.hpp
  src/utils/Chrono.hpp
  src/utils/ConfigStruct.hpp
  src/utils/Keys.cpp
  src/utils/Keys.hpp
Labels: documentation

#101 :globe_with_meridians:Fix network communications
  doc/Doxyfile
  plugins/components/acceleration/Acceleration.hpp
  plugins/components/collider/Collider.hpp
  plugins/components/controllable/Controllable.hpp
  plugins/components/damage/Damage.hpp
  plugins/components/deathRange/DeathRange.hpp
  plugins/components/gun/Gun.hpp
  plugins/components/health/Health.hpp
  plugins/components/position/Position.hpp
  plugins/components/scale/Scale.hpp
  plugins/components/spriteId/SpriteID.hpp
  plugins/components/type/Type.hpp
  plugins/components/velocity/Velocity.hpp
  plugins/components/visible/Visible.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/attack/Attack.hpp
  plugins/systems/attack/CMakeLists.txt
  plugins/systems/input/CMakeLists.txt
  plugins/systems/input/Input.cpp
  plugins/systems/input/Input.hpp
  plugins/systems/move/Move.cpp
  plugins/systems/sfml/Display.cpp
  plugins/systems/sfml/Sfml.cpp
  plugins/systems/sfml/SpriteComponent.hpp
  plugins/systems/sfml/Texture.cpp
  src/ECS/registry/Registry.hpp
  src/client/CMakeLists.txt
  src/client/Main.cpp
  src/client/configClient.cfg
  src/network/RTypeClient.cpp
  src/network/RTypeClient.hpp
  src/network/UDPServer.cpp
  src/network/UDPServer.hpp
  src/server/Main.cpp
  src/utils/ComponentUtils.hpp
  src/utils/Projectile.cpp
  src/utils/Projectile.hpp
Labels: server, client, network

#107 Client inputs sent to server
  plugins/components/controllable/Controllable.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/collision/Collision.cpp
  plugins/systems/input/Input.cpp
  plugins/systems/move/Move.cpp
  plugins/systems/sfml/Display.cpp
  plugins/systems/sfml/Input.cpp
  src/client/Main.cpp
  src/network/RTypeClient.cpp
  src/network/RTypeClient.hpp
  src/network/UDPServer.cpp
  src/network/UDPServer.hpp
  src/server/Main.cpp
Labels: server, client, network

#105 :sparkles: Action component
  assets/player-shoot-forward-left.png
  assets/player-shoot-forward-right.png
  assets/player-shoot-forward.png
  assets/player-shoot-left.png
  assets/player-shoot-right.png
  assets/shot5.png
  assets/spsheet1shoot.png
  config/textures.cfg
  plugins/components/action/Action.cpp
  plugins/components/action/Action.hpp
  plugins/components/action/CMakeLists.txt
  plugins/components/controllable/Controllable.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/sfml/ActionManager.cpp
  plugins/systems/sfml/ActionManager.hpp
  plugins/systems/sfml/CMakeLists.txt
  plugins/systems/sfml/Input.cpp
  plugins/systems/sfml/Input.hpp
  plugins/systems/sfml/Sfml.cpp
  plugins/systems/sfml/Sfml.hpp
  plugins/systems/sfml/SpriteComponent.hpp
  plugins/systems/sfml/Texture.hpp
  src/utils/EntityActions.cpp
  src/utils/EntityActions.hpp
Labels: enhancement, game-engine, graphic

#109 :recycle: Fix controllable component
  plugins/components/controllable/Controllable.hpp
  src/utils/Keys.hpp
Labels: bug

#108 :sparkles: Accessibility > colorblindness shaders
  config/shaders.cfg
  plugins/systems/sfml/CMakeLists.txt
  plugins/systems/sfml/Display.cpp
  plugins/systems/sfml/Display.hpp
  plugins/systems/sfml/Sfml.cpp
  plugins/systems/sfml/Shader.cpp
  plugins/systems/sfml/Shader.hpp
  shaders/deuteranopia.frag
  shaders/protanopia.frag
  shaders/tritanopia.frag
  src/client/configClient.cfg
Labels: enhancement, graphic

#111 :zap: :globe_with_meridians: Client network optimization
  src/client/Main.cpp
  src/network/RTypeClient.cpp
  src/network/RTypeClient.hpp
Labels: client, network

#115 Add raylib graphic dependency
  .github/workflows/rtype.yaml
  flake.nix
  src/CMakeLists.txt
  src/client/CMakeLists.txt
Labels: client

#116 :adhesive_bandage: Fix crash at random time
  src/client/Main.cpp
  src/network/RTypeClient.cpp
  src/network/RTypeClient.hpp
  src/network/UDPServer.cpp
Labels: bug, client
