Repository Tugduoff/RType, pull requests merged in 2024-11, with the labels that each got.

#113 Behavior system
  config/config.cfg
  plugins/components/Ai/Ai.cpp
  plugins/components/Ai/Ai.hpp
  plugins/components/Ai/CMakeLists.txt
  plugins/components/gun/Gun.cpp
  plugins/components/gun/Gun.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/behavior/Behavior.cpp
  plugins/systems/behavior/Behavior.hpp
  plugins/systems/behavior/CMakeLists.txt
  plugins/systems/input/Input.cpp
  src/server/Main.cpp
  src/server/configServer.cfg
Labels: enhancement, game-engine

#112 :sparkles: First implementation of the Sound component.
  assets/death.wav
  assets/hit.wav
  assets/laser.wav
  assets/laser2.wav
  assets/spawn.wav
  config/config.cfg
  plugins/components/gun/Gun.cpp
  plugins/components/gun/Gun.hpp
  plugins/components/sound/CMakeLists.txt
  plugins/components/sound/Sound.cpp
  plugins/components/sound/Sound.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/collision/Collision.cpp
  plugins/systems/collision/Collision.hpp
  plugins/systems/config/Config.cpp
  plugins/systems/input/Input.cpp
  plugins/systems/sfml/ActionManager.cpp
  plugins/systems/sfml/CMakeLists.txt
  plugins/systems/sfml/Display.cpp
  plugins/systems/sfml/Sfml.cpp
  plugins/systems/sfml/Sfml.hpp
  plugins/systems/sfml/SfmlSoundComponent.hpp
  plugins/systems/sfml/SoundSystem.cpp
  plugins/systems/sfml/SoundSystem.hpp
  plugins/systems/sfml/SpriteComponent.hpp
  src/client/Main.cpp
  src/server/Main.cpp
Labels: enhancement, game-engine, graphic

#114 :sparkles: Death effect
  assets/explosion.png
  config/config.cfg
  config/textures.cfg
  plugins/components/destruction/CMakeLists.txt
  plugins/components/destruction/Destruction.cpp
  plugins/components/destruction/Destruction.hpp
  plugins/components/position/Position.hpp
  plugins/components/scale/Scale.hpp
  plugins/components/sound/Sound.hpp
  plugins/components/spriteId/SpriteID.hpp
  plugins/systems/attack/Attack.cpp
  plugins/systems/collision/Collision.cpp
  plugins/systems/collision/Collision.hpp
  src/client/Main.cpp
  src/server/Main.cpp
  src/server/configServer.cfg
Labels: enhancement, game-engine, graphic

#119 :sparkles: :building_construction: Config editor
  build_config_editor.sh
  configEditor/CMakeLists.txt
  configEditor/Gui.cpp
  configEditor/Gui.hpp
  configEditor/Main.cpp
  configEditor/gui_window_file_dialog.h
  configEditor/raygui.h
  plugins/systems/config/Config.cpp
  plugins/systems/config/Config.hpp
  src/utils/ConfigStruct.hpp
Labels: feur

#120 :sparkles: Udp init refactor
  config/config.cfg
  plugins/components/action/Action.hpp
  plugins/components/controllable/Controllable.hpp
  plugins/systems/sfml/Input.cpp
  plugins/systems/sfml/Input.hpp
  src/ECS/entity/EntityManager.hpp
  src/GameEngine/ComponentsGetter.hpp
  src/GameEngine/GameEngine.cpp
  src/GameEngine/GameEngine.hpp
  src/client/Main.cpp
  src/network/RTypeClient.cpp
  src/network/RTypeClient.hpp
  src/network/UDPConnection.cpp
  src/network/UDPServer.cpp
  src/network/UDPServer.hpp
  src/server/Main.cpp
Labels: enhancement, network
